### ISSUE TITLE
Already exist rosarior/awesome-django

### ISSUE THREAD

**Issue by avelino** [wsvincent/awesome-django#1]
Why not unify the content?
https://github.com/rosarior/awesome-django

**Comment by wsvincent** [comment]
That repo is good too. I think there's room for multiple "awesome-Django" repos.

I wanted something that was a little smaller and more Greatest Hits focused. It's easy to just add add add and then you have a list that's so comprehensive it's hard to use. That's my bias anyway.

I'm very open to PRs but I want this list to intentionally not be a long one.
