### ISSUE TITLE
Suggestion: Add async/ASGI support symbol or similar to packages that support these technologies

### ISSUE THREAD

**Issue by JonasKs** [wsvincent/awesome-django#110]
With Django3.1 out and 3.2 just around the corner it would be beneficial to me to know which packages is fully async/ASGI compatible and which are not. 

As an example, [django-guid](https://github.com/snok/django-guid) version 2.2.0 does not support ASGI due to using of threading, which obviously will break in an ASGI environment. Most requests will have the same thread, so the entire logic falls apart. With the new release coming up(not pushed yet, will most likely be this week), it will have full ASGI support. I assume there is plenty more packages like this, or which has huge performance impact of being async. I'd love if I could see an `ASGI` or `async` mark behind the package name if it's updated to support these technologies.

**Comment by wsvincent** [comment]
Hi @JonasKs,

That's a great idea, albeit a bit more work for @webology and me! I don't know of a dedicated asgi support site or flag, though it does seem needed for future Django versions I agree.

For now I'm going to close this but it's something we need to sort out as async becomes more prevalent in the 3rd party ecosystem.

Cheers,

Will

**Comment by JonasKs** [comment]
No worries @wsvincent, I understand that would cause more work for you to maintain. I just released [Django-GUID](https://github.com/snok/django-guid) with ASGI and async support. Would you mind me making a PR changing the title to include that it supports ASGI and Django3.1, or would you prefer not having anything like that in the list at all?
