### ISSUE TITLE
deployment section

### ISSUE THREAD

**Issue by mjhea0** [wsvincent/awesome-django#12]
@wsvincent want to add a deployment section? 

https://testdriven.io/blog/production-django-deployments-on-heroku/

**Comment by wsvincent** [comment]
Hey @mjhea0, I think I want to keep it simple as is. Easy for these repos to bloat out. TestDriven is already listed so I think sticking to site-wide resources rather than article by article, for now, is the way to go. Change my mind when I see you :)
