### ISSUE TITLE
Suggeston: Please add django-base-site

### ISSUE THREAD

**Issue by epicserve** [wsvincent/awesome-django#134]
Please consider adding https://github.com/epicserve/django-base-site/. I'm the author and I try to keep it updated. If not considered worthy, then please provide friendly feedback on what you would like to see changed.

**Comment by wsvincent** [comment]
Looks like a cool package. Thx for pinging us. Added and will be featured on Django News newsletter in the coming weeks.

**Comment by epicserve** [comment]
@wsvincent,

Gulp! 😳

I've already had one bug reported since you added it that I fixed. Hopefully, I can find time to keep on improving it.
