### ISSUE TITLE
[proposal] Split fields from models section?

### ISSUE THREAD

**Issue by fabiocaccamo** [wsvincent/awesome-django#181]
What do you think about splitting fields from the models section? 
Maybe a model subsection could be a good solution.
If you agree I can submit a PR.

**Comment by jefftriplett** [comment]
That sounds like an excellent idea.

**Comment by fabiocaccamo** [comment]
Will do, will do ... :)

**Comment by ulgens** [comment]
Not sure why the bot closed this as completed but they still seem together.

**Comment by jefftriplett** [comment]
Semi-fixed for real. We might have be off a field or two.
