### ISSUE TITLE
🤔 Issue template ideas

### ISSUE THREAD

**Issue by jefftriplett** [wsvincent/awesome-django#193]
We need an issue template to help with some expectations. Here is my quick riff on what we might want: 

----

Our goal with Awesome Django is to highlight packages that we think are awesome and stand out above the rest. 

Our goal isn't to be a comprehensive directory of 1000+ projects like [Django Packages](https://djangopackages.org).

We are looking for projects that are:
- relevant to Django
- maintained
- release and support history
- stand out because they are useful and solve a unique problem
- we can't ignore your star count, but we don't have a high number in mind. 

What we are NOT looking out for:
- unmaintained projects
- promote your project, service, or employer

---- 

- [ ] What makes this product awesome? 
- [ ] Are you the author or a maintainer? (no points off for self-promotion)
- [ ] If your project is brand new, we don't have a minimum number of GH stars, but your project needs "enough" stars.
- [ ] Is this project maintained?
- [ ] If your project is published on PyPI, is there a history/pattern of keeping it updated?
- [ ] If your project/service is a paid product, do you work for the same company? (emphasis on disclosure vs. promoting your product/service/company)
- [ ] Django and Python are trademarked by their respective foundations, if your product, paid service, and/or domain name use these trademarks, do you have their permission to do so?

**Comment by wsvincent** [comment]
Yes, agreed. I will try to tackle this week.

**Comment by jefftriplett** [comment]
@wsvincent I added two template which we can work on/improve, but maybe these will help with the original intent of this ticket:

- https://github.com/wsvincent/awesome-django/blob/main/.github/issue_template.md
- https://github.com/wsvincent/awesome-django/blob/main/.github/pull_request_template.md

Feel free to re-word/re-work or mention to me and I'll update it as we go.

**Comment by jefftriplett** [comment]
This is mostly baked along with my script which scores the submissions. Now I think I need to encourage people to open PRs instead of issues for suggestions.
