### ISSUE TITLE
django-bleach

### ISSUE THREAD

**Issue by marksweb** [wsvincent/awesome-django#195]
I've just been reading through the list of packages and noted that bleach is listed as something that works well with django, but django-bleach isn't listed.

It's a mature package, first released 10 years ago, and makes integrating bleach to models and forms really simple.

https://github.com/marksweb/django-bleach

https://pypi.org/project/django-bleach/

Perhaps I could raise a PR to add this in - perhaps the forms section?

**Comment by wsvincent** [comment]
Hi @marksweb,

Yes I agree it does seem worthy of inclusion. Please do raise a PR and we'll merge. Thx!
