### ISSUE TITLE
Add `ReactPy` to awesome-django

### ISSUE THREAD

**Issue by Archmonger** [wsvincent/awesome-django#213]
As the name implies, ReactPy is a python port of ReactJS.

Our Django support is relatively new, but `ReactPy` core is fairly old/stable. We are trying to get some more exposure to see what kind of django-specific features need development.

See here for project info: https://github.com/reactive-python/reactpy

**Comment by jefftriplett** [comment]
The project looks interesting. I suspect reactpy-django would be the better fit, but I was struggling to find examples of how to use it. 

I also stumbled on https://forum.djangoproject.com/t/reactpy-build-reactjs-interfaces-in-pure-python/19913 and was curious about the status of the demo? I'm not sure either of these are a deal breaker, but passing it along.

**Comment by Archmonger** [comment]
@jefftriplett The demos on our documentation are fully working. There was only a short period of time in-between renaming the project where they were broken.

**Comment by Archmonger** [comment]
Also, all examples can be found in the [reactpy core](https://reactpy.dev/docs/index.html) documentation.

**Comment by jefftriplett** [comment]
@Archmonger apologies for letting this get away from us. If you want to convert this into a pull request and reference this issue number, we'd be happy to accept it.

**Comment by Archmonger** [comment]
Would you like me to add our core package, or our Django compatibility module?
