### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ndsvw** [wsvincent/awesome-django#221]
Hello, I found some broken hyperlinks:
- [ ] http://dokku.viewdocs.io/dokku/ (file: README.md, status code: 503)
- [ ] https://wsvincent.com/django-rest-framework-tutorial/ (file: README.md, status code: 404)
- [ ] https://wsvincent.com/django-rest-framework-react-tutorial/ (file: README.md, status code: 404)

**Comment by jefftriplett** [comment]
@ndsvw thank you for pointing these out. these should be fixed now.

^^ cc @wsvincent - I looked to see if both of these articles were moved and I'm not seeing them. cc'ed you in case you want to re-link them to their new homes.
