### ISSUE TITLE
Request to Add django-modeltranslation to Awesome Django List

### ISSUE THREAD

**Issue by bvedad** [wsvincent/awesome-django#224]
## Project Information

1. **Project Name:** django-modeltranslation
2. **Project URL:** [https://github.com/deschler/django-modeltranslation](https://github.com/deschler/django-modeltranslation)
3. **Description:** Django-modeltranslation is a Django app that provides an easy way to translate Django model fields.

## Criteria

Please answer the following questions about the project you are submitting. This will help us evaluate if the project should be included in the Awesome Django list.

1. **Is the project new?**
   - [ ] Yes
   - [x] No

2. **How long has the project been maintained?**
   Approximately 4 years.

3. **How many releases has it had if it's a library or package?**
   The project has had multiple releases. The release history can be found at: [https://github.com/deschler/django-modeltranslation/releases](https://github.com/deschler/django-modeltranslation/releases)

4. **Are you the author or are you submitting the project on behalf of a company?**
   - [ ] I am the author
   - [x] I am submitting on behalf of a company
   - [ ] Other (please specify)

5. **What makes it awesome?**
   Django-modeltranslation is a valuable addition to the Awesome Django list because it provides a seamless way to translate Django model fields, allowing developers to easily build multilingual websites or applications. It offers a simple and intuitive API to define translated fields and handles the database schema and form serialization automatically. This greatly simplifies the process of managing translations within Django projects and contributes to making Django a powerful and versatile framework for building internationalized applications.

## Additional Information

The project has comprehensive documentation available at: [https://django-modeltranslation.readthedocs.io/](https://django-modeltranslation.readthedocs.io/)

It has a strong community support with a considerable number of stars, forks, and active contributors on GitHub.

Django-modeltranslation has been widely adopted and successfully used in various production applications. It has proven to be reliable and efficient in handling multilingual content, and it continues to receive maintenance and updates from the community.

Thank you for considering adding django-modeltranslation to the Awesome Django list!

**Comment by jefftriplett** [comment]
@bvedad, apologies for letting this get away from us. If you want to convert this into a pull request and reference this issue number, we'd be happy to accept it.
