### ISSUE TITLE
Request to add graphene-django-filter

### ISSUE THREAD

**Issue by thomas-arun** [wsvincent/awesome-django#225]
## Project Information

1. **Project Name:** [graphene-django-filter](https://pypi.org/project/graphene-django-filter/)
2. **Project URL:** https://github.com/devind-team/graphene-django-filter
3. **Description:** This package contains advanced filters for [graphene-django](https://github.com/graphql-python/graphene-django). The standard filtering feature in `graphene-django` relies on the [django-filter](https://github.com/carltongibson/django-filter) library and therefore provides the flat API without the ability to use logical operators such as `and`, `or` and `not`

## Criteria

1. **Is the project new?**
   - [ ] Yes
   - [x] No

2. **How long has the project been maintained?**
   Approximately 1.5 years

3. **How many releases has it had if it's a library or package?**
  https://github.com/devind-team/graphene-django-filter/releases

4. **Are you the author or are you submitting the project on behalf of a company?**
   - [ ] I am the author
   - [ ] I am submitting on behalf of a company
   - [X] Other - I am a contributor

5. **What makes it awesome?**
   This library helps in adding advanced filtering capabilities on top of existing `graphene-django` package in a very minimally invasive way. The standard filtering feature in `graphene-django` relies on the [django-filter](https://github.com/carltongibson/django-filter) library and therefore provides the flat API without the ability to use logical operators such as and, or and not. This library makes the API nested and adds logical expressions by extension of the `DjangoFilterConnectionField` field and the `FilterSet` class. Also, the library provides some other convenient filtering features.

## Additional Information

This project is successfully being used in production by many teams, and is a life saver for existing graphene-django based projects which need advanced filtering capability. Automated build actions including test suite runner, coverage and coveralls are set up for this project ensuring new versions are bug free.

**Coverage from latest build (as of June 2023):** https://coveralls.io/jobs/123065040

Thank you for considering adding `graphene-django-filter` to the Awesome Django list!

**Comment by jefftriplett** [comment]
@thomas-arun This looks useful. If you want to convert this into a pull request and reference this issue number, we'd be happy to accept it.

**Comment by thomas-arun** [comment]
Thank you for your review @jefftriplett. I will open a PR and attach it.
