### ISSUE TITLE
Sequence request

### ISSUE THREAD

**Issue by TareqMonwer** [wsvincent/awesome-django#26]
Hello Vincent!
Can you please order books by 'level' as beginner, intermediate, expert/for professionals?

It will help people to choose right book for themselves.

**Comment by wsvincent** [comment]
That's a good idea. Given there are so few though I'm not sure it's worth it. For example, still I believe I'm the only author with Django 2.2 books. In general books will be more intermediate/advanced focused.

As more books are written I'll keep this in mind but for now I think not enough to warrant the distinctions.
