### ISSUE TITLE
request to add `django-role-permissions`

### ISSUE THREAD

**Issue by krystofbe** [wsvincent/awesome-django#270]
## Project Information

1. **Project Name:** django-role-permissions
2. **Project URL:** https://github.com/vintasoftware/django-role-permissions
3. **Description:** django-role-permissions is a Django app for role-based permissions. It simplifies the management of user roles and their associated permissions, making it easier to enforce security policies in Django applications.

## Criteria

Please answer the following questions about the project you are submitting. This will help us evaluate if the project should be included in the Awesome Django list.

1. **Is the project new?**
   - [ ] Yes
   - [x] No

2. **How long has the project been maintained?**
   The project has been maintained for more than 10 years.

3. **How many releases has it had if it's a library or package?**
   There have been 35 releases. [Link to release history](https://github.com/vintasoftware/django-role-permissions/releases)

4. **Are you the author or are you submitting the project on behalf of a company?**
   - [ ] I am the author
   - [ ] I am submitting on behalf of a company
   - [x] I just found out about awesome-django because you talked about it in the postcast. Since I use django-role-permissions in almost every django project, I thought it would be nice to see it here (I have no connection to the authors, just a happy user).

5. **What makes it awesome?**
   django-role-permissions stands out due to its simplicity and effectiveness in managing role-based permissions. It is well-documented, actively maintained, and integrates seamlessly with Django projects. The package offers a straightforward API, making it easy to define and enforce permissions without complicating the application's codebase.

## Additional Information

django-role-permissions is backed by a robust test suite and has a supportive community. The project is well-documented, ensuring that developers can quickly get up to speed and integrate it into their projects. Additionally, it provides flexibility by allowing developers to define custom roles and permissions tailored to their specific application needs.

**Comment by krystofbe** [comment]
just a side note: `django-guardian` which is listed under `General` does object based permissions, which is kind of the same topic as this package. would it make sense to add a section called "permissions/roles/groups" or something?

**Comment by jefftriplett** [comment]
Hi @krystofbe, +1 to including this and +1 for the `permissions/roles/groups` category. Those would both be welcome. 

If you don't mind creating a PR with the changes, I'm happy to quickly approve them.

**Comment by krystofbe** [comment]
Hi @jefftriplett.

I added a permissions section in https://github.com/wsvincent/awesome-django/pull/272, I also added django-rules that I use regularly, hope it's ok to put these two in one PR

**Comment by jefftriplett** [comment]
@krystofbe works for me. Thank you for the addition!
