### ISSUE TITLE
Archived content being linked to

### ISSUE THREAD

**Issue by qvisty** [wsvincent/awesome-django#278]
When opening: [docker-django](https://github.com/erroneousboat/docker-django/) - A quick starter guide for Django and Docker together:

> This repository has been archived by the owner on Dec 17, 2021. It is now read-only.

I suggest it has changed status to "not being that awesome anymore" 😉

**Comment by wsvincent** [comment]
Agree. Thanks for the Issue!

https://github.com/wsvincent/awesome-django/commit/50f49d80b2ceb138b6d06d7c127a512e723e3b10
