### ISSUE TITLE
Should I submit a few of my packages here?

### ISSUE THREAD

**Issue by matthiask** [wsvincent/awesome-django#285]
Hey,

Thanks for maintaining this list. I do not want to submit multiple pull requests without asking first if I should do that (since it's work for you and also for me)

I have a few projects which might be interesting for this curation. All projects are several or even many years old and still are still in active maintenance or even development except where noted.

## Admin

https://github.com/feincms/django-content-editor -- Supercharged inlines where inline models may be mixed. Useful for building a block-based CMS.

## Content Management Systems

https://github.com/feincms/feincms3

FeinCMS is mentioned but it's mostly in maintenance mode. feincms3 is smaller, more focussed, better documented and in active development.

## Editors

https://github.com/matthiask/django-prose-editor/

ProseMirror-based HTML editor for Django. This is a newer project, only six months old. I'm releasing new updates regularly and actively working on it. 

## Files/Images

https://github.com/matthiask/django-imagefield

Another image field for Django. It goes to extreme lengths to verify that Pillow can actually work with uploaded images. It also supports predefining image processing pipelines and doesn't need a cache to stay fast.

https://github.com/feincms/django-cabinet

A media library for Django, modeled after django-filer but much simpler and with better visual integration into the Django administration interface.

## Internationalisation

https://github.com/matthiask/django-translated-fields

Django model translation without magic. Here's a blog post on it: https://406.ch/writing/django-translated-fields-localized-model-fields-without-magic/ . I thought the DjangoCon talk by Raphael Michel also included it in the comparison but it seems I was mistaken, but maybe it's interesting anyway. See https://www.youtube.com/watch?v=4WEMXydnQs8 and https://github.com/raphaelm/django-i18n-demoapp

## Models

https://github.com/feincms/django-tree-queries 

django-mptt is still mentioned even though its maintenance status is unclear, see https://github.com/django-mptt/django-mptt/commit/6f6c1c485f3adc1d579f8d22e0279ce1d52334f6 and https://406.ch/writing/django-tree-queries/
The number of sites I have which still use django-mptt is steadily declining and I'm not sure how long I'm continuing the disgruntled maintenance of the package. It's maybe better not to advertise it anymore?

## Users

https://github.com/matthiask/django-authlib

Utilities for logging in using magic links or Google/Facebook single sign on and role-based permissions. Maybe I'm going to rebuild it on top of https://github.com/carltongibson/django-unique-user-email soon...

---

Thanks! And feel free to spend no or only little time on this. At the very least I could use it as a start of a projects page of my own, a thing I have wanted to do for a long time.

**Comment by jefftriplett** [comment]
With DjangoCon US travel for me starting on Friday, I might not get to this, this week. 

60-second overview of what we tend to prioritize (which loosely aligns with the original template). 

That said, we loosely look for >100 stars but make a few exceptions (rarely, <50 stars). We also look at releases and if the project is maintained. Also, how clear is the path to get docs and setup information? 

(more when I get a sec)

**Comment by matthiask** [comment]
> That said, we loosely look for >100 stars but make a few exceptions (rarely, <50 stars). We also look at releases and if the project is maintained. Also, how clear is the path to get docs and setup information?

I think that's an excellent rule of thumb.

django-prose-editor, django-imagefield, django-translated-fields and django-tree-queries all have over 100 stars, but mostly only just. 

I think django-content-editor might be almost more interesting than the others because extending the Django admin itself with CMS functionality instead of replacing the admin (like Wagtail or django CMS) is quite unique. That being said, https://github.com/raagin/django-streamfield also exists and could maybe also be suitable for inclusion. I don't know.

**Comment by jefftriplett** [comment]
Why don't you pick an arbitrary number of the best of these (maybe pick three or four) and submit those as PRs?

I will probably do some work on this over the holiday break, which will reshape how things are included medium to long term since we have a bit of a Hotel California situation with what is included. it's also a bit of a maintenance burden for us. 

I'm going to close this, but you are welcome to submit some PRs.
