### ISSUE TITLE
Request addition to awesome list

### ISSUE THREAD

**Issue by MeNsaaH** [wsvincent/awesome-django#5]
The other [Awesome-django](https://github.com/rosarior/awesome-django) link recorded in the [Awesome List](https://github.com/sindresorhus/awesome) is broken, my guess is that the repo has being deleted.

Why not request a replacement?

**Comment by mjhea0** [comment]
https://github.com/sindresorhus/awesome/pull/1484

**Comment by MeNsaaH** [comment]
https://github.com/sindresorhus/awesome/pull/1477 it just got fixed

**Comment by mjhea0** [comment]
huh?

**Comment by MeNsaaH** [comment]
The issue got fixed by a PR yesterday. They removed the django link and told the @wsvincent to submit a PR for his repo

**Comment by wsvincent** [comment]
Thanks both of you. I'm currently updating the repo and will submit directly.

**Comment by wsvincent** [comment]
Here's the PR btw.

https://github.com/sindresorhus/awesome/pull/1477
