### ISSUE TITLE
Actionable Django: A Django Course for Python Developers

### ISSUE THREAD

**Issue by ndunn219** [wsvincent/awesome-django#96]
Hey there. Would you all be willing to add [Actionable Django: A Django Course for Python Developers](https://www.amazon.com/Actionable-Django-Course-Python-Developers/dp/1951959043) to the 3.1 book list? I'd be happy to send you a copy to review if you like.

Thanks,

Nat

**Comment by wsvincent** [comment]
Hi Nat, Yes please send a copy. You know my email. -Will
