### ISSUE TITLE
Add fork me on GitHub info/wording

### ISSUE THREAD

**Issue by jefftriplett** [wsvincent/awesome-django#98]
We could use some more obvious copy on the website for info on how to fork on GitHub: https://awesomedjango.org/

This can go in `_includes/header.html` or `_includes/footer.html`.

**Comment by Markel** [comment]
Hi! I would be interested to take part :)

I was wondering that nor `_layouts/header.html` nor `_layouts/footer.html` files exist. Maybe you meant the ones inside the `_includes` folder?

**Comment by jefftriplett** [comment]
@Markel sorry about that, updated to mention `_includes`. If you have ideas and want to post a pull request, we'd appreciate it.

**Comment by Markel** [comment]
Yeah, I will submit a PR, probably tomorrow afternoon (Europe Time)

**Comment by YASH3166** [comment]
Hi! I would be interested to take part :)

**Comment by Red-0111** [comment]
Please assign will try my best

**Comment by ish-u** [comment]
hello,
I am a newbie , do i need to add ribbon html from this site https://github.blog/2008-12-19-github-ribbons/
in the header and footer file
